import{a as R,S as B,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const E="https://pixabay.com/api/",I="53389241-61d9b890c2cc3baebfd2ae29c";async function h(t,r=1){const o=await R.get(E,{params:{key:I,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return{hits:o.data.hits,totalHits:o.data.totalHits}}const f=document.querySelector(".gallery"),y=document.querySelector(".load-more-button"),M=new B(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:200});function p(t){if(!t||t.length===0)return;const r=t.map(o=>{const{webformatURL:a,largeImageURL:e,tags:s,likes:l,views:w,comments:q,downloads:v}=o;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img class="gallery-img" src="${a}" alt="${s}" loading="lazy"/>
        </a>
        <div class="details">
          <p class="details-item"><b>Likes</b> ${l}</p>
          <p class="details-item"><b>Views</b> ${w}</p>
          <p class="details-item"><b>Comments</b> ${q}</p>
          <p class="details-item"><b>Downloads</b> ${v}</p>
        </div>
      </li>`}).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function P(){f.innerHTML=""}function i(){y.classList.add("hidden")}function b(){y.classList.remove("hidden")}function L(t){(t??document.querySelector(".loader")).classList.remove("hidden")}function S(t){(t??document.querySelector(".loader")).classList.add("hidden")}const H=document.querySelector(".form"),$=document.querySelector("input"),A=document.querySelector(".load-more-button"),m=document.querySelector(".loader"),g=document.querySelector(".load-more-loader");let u="",d=1,c=0;H.addEventListener("submit",O);A.addEventListener("click",x);async function O(t){t.preventDefault();const r=$.value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}u=r,d=1,c=0,P(),i(),L(m);try{const{hits:o,totalHits:a}=await h(u,d);if(c=a??0,!o||o.length===0){i(),n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(o),document.querySelectorAll(".gallery a").length>=c?(i(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{i(),n.error({title:"Error",message:"Something went wrong while fetching images. Please try again later.",position:"topRight"})}finally{S(m)}}async function x(){d++,L(g),i();try{const{hits:t}=await h(u,d);if(!t||t.length===0){n.info({message:"We're sorry, but there are no more images to load.",position:"topRight"}),i();return}p(t),document.querySelectorAll(".gallery a").length>=c?(i(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b();const o=document.querySelector(".gallery a");if(o){const{height:a}=o.getBoundingClientRect();scrollBy({top:a*2,behavior:"smooth"})}}catch{n.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}finally{S(g)}}
//# sourceMappingURL=index.js.map
