import{a as R,S as B,i}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const E="https://pixabay.com/api/",M="53389241-61d9b890c2cc3baebfd2ae29c";async function h(t,r=1){const o=await R.get(E,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return{hits:o.data.hits,totalHits:o.data.totalHits}}const f=document.querySelector(".gallery"),y=document.querySelector(".load-more-button"),P=new B(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:200});function p(t){if(!t||t.length===0)return;const r=t.map(o=>{const{webformatURL:a,largeImageURL:e,tags:s,likes:n,views:w,comments:q,downloads:v}=o;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img class="gallery-img" src="${a}" alt="${s}" loading="lazy"/>
        </a>
        <div class="details">
          <p class="details-item"><b>Likes</b> ${n}</p>
          <p class="details-item"><b>Views</b> ${w}</p>
          <p class="details-item"><b>Comments</b> ${q}</p>
          <p class="details-item"><b>Downloads</b> ${v}</p>
        </div>
      </li>`}).join("");f.insertAdjacentHTML("beforeend",r),P.refresh()}function H(){f.innerHTML=""}function l(){y.classList.add("hidden")}function L(){y.classList.remove("hidden")}function b(t){(t??document.querySelector(".loader")).classList.remove("hidden")}function S(t){(t??document.querySelector(".loader")).classList.add("hidden")}const $=document.querySelector(".form"),A=document.querySelector("input"),I=document.querySelector(".load-more-button"),m=document.querySelector(".loader"),g=document.querySelector(".load-more-loader");let d="",c=1,u=0;$.addEventListener("submit",O);I.addEventListener("click",x);async function O(t){t.preventDefault();const r=A.value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}d=r,c=1,H(),l(),b(m);try{const{hits:o,totalHits:a}=await h(d,c);if(u=a,!o||o.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(o),o.length>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{i.error({title:"Error",message:"Something went wrong while fetching images. Please try again later.",position:"topRight"})}finally{S(m)}}async function x(){c++,b(g),l();try{const{hits:t}=await h(d,c);p(t),document.querySelectorAll(".gallery a").length>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L();const o=document.querySelector(".gallery a");if(o){const{height:a}=o.getBoundingClientRect();scrollBy({top:a*2,behavior:"smooth"})}}catch{i.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}finally{S(g)}}
//# sourceMappingURL=index.js.map
