import{a as R,S as B,i}from"./assets/vendor-DvfmeZXB.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const M="https://pixabay.com/api/",P="53389241-61d9b890c2cc3baebfd2ae29c";async function h(t,a=1){const o=await R.get(M,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}});return{hits:o.data.hits,totalHits:o.data.totalHits}}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more-button");document.querySelector(".load-more-loader");const H=new B(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:200});function L(t){if(!t||t.length===0)return;const a=t.map(o=>{const{webformatURL:s,largeImageURL:e,tags:r,likes:n,views:q,comments:v,downloads:E}=o;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img class="gallery-img" src="${s}" alt="${r}" loading="lazy"/>
        </a>
        <div class="details">
          <p class="details-item"><b>Likes</b> ${n}</p>
          <p class="details-item"><b>Views</b> ${q}</p>
          <p class="details-item"><b>Comments</b> ${v}</p>
          <p class="details-item"><b>Downloads</b> ${E}</p>
        </div>
      </li>
    `}).join("");f.insertAdjacentHTML("beforeend",a),H.refresh()}function $(){f.innerHTML=""}function l(){p.classList.add("hidden")}function b(){p.classList.remove("hidden")}function S(t=y){t.classList.remove("hidden")}function w(t=y){t.classList.add("hidden")}const A=document.querySelector(".form"),I=document.querySelector("input"),O=document.querySelector(".load-more-button"),m=document.querySelector(".loader"),g=document.querySelector(".load-more-loader");let d="",c=1,u=0;A.addEventListener("submit",x);O.addEventListener("click",D);async function x(t){t.preventDefault();const a=I.value.trim();if(!a){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}d=a,c=1,$(),l(),S(m);try{const{hits:o,totalHits:s}=await h(d,c);if(u=s,!o||o.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(o),o.length>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{i.error({title:"Error",message:"Something went wrong while fetching images. Please try again later.",position:"topRight"})}finally{w(m)}}async function D(){c++,S(g),l();try{const{hits:t}=await h(d,c);L(t),document.querySelectorAll(".gallery a").length>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b();const o=document.querySelector(".gallery a");if(o){const{height:s}=o.getBoundingClientRect();scrollBy({top:s*2,behavior:"smooth"})}}catch{i.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}finally{w(g)}}
//# sourceMappingURL=index.js.map
